context:
  version: "0.1.4"

package:
  name: rustfits
  version: ${{ version }}

source:
  url: https://github.com/esheldon/rustfits/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 5e911ae939b3b7e542bfde788335a26220ec25aff0cd6faefacbd4bdd1aae6b2

build:
  number: 0
  python:
    version_independent: true
  skip:
    - is_abi3 and not is_python_min
  script:
    - if: unix
      then:
        - maturin build -v -j ${CPU_COUNT} --release --strip --manylinux off --interpreter=${PYTHON} --features pyo3/abi3-py${{ python_min|replace(".", "") }}
      else:
        - maturin build -v -j %CPU_COUNT% --release --strip --manylinux off --interpreter=%PYTHON% --features pyo3/abi3-py${{ python_min|replace(".", "") }}
    # ^add this flag for cross-compile later maybe? -Zfeatures=itarget
    - if: unix
      then:
        - ${PYTHON} -m pip install ${SRC_DIR}/target/wheels/rustfits*.whl --no-deps -vv --no-build-isolation
      else:
        - cd target/wheels
        - chcp 65001
        - set PYTHONUTF8=1
        - set PYTHONIOENCODING="UTF-8"
        - set TMPDIR=tmpbuild_%PY_VER%
        - FOR %%w in (*.whl) DO %PYTHON% -m pip install %%w --no-clean --no-deps -vv --no-build-isolation
        - cd ..
        - cd ..
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - python-abi3
    - pip
    - maturin >=1.7,<2.0a0
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - rustfits
        - rustfits._rust
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - if: build_platform == target_platform
    then:
      script:
        - if: unix
          then:
            - abi3audit ${SP_DIR}/rustfits/*.so -s -v --assume-minimum-abi3 ${{ python_min }}
          else:
            - abi3audit %SP_DIR%/rustfits/_rust.pyd -s -v --assume-minimum-abi3 ${{ python_min }}
      requirements:
        run:
          - abi3audit
  # we run tests since they are fast...
  - if: unix
    then:
      script:
        - pytest -vv tests
      files:
        source:
          - tests/
      requirements:
        run:
          - pytest
          - astropy
          - fitsio
          - aioftp

about:
  homepage: https://github.com/esheldon/rustfits
  summary: A python FITS library with extension in rust
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - beckermr
    - esheldon
